theme: jekyll-theme-minimal
title: Moe Sunami
description: I am taking a year to learn from digital rights and grassroots advocacy groups across the world. I am especially interested in forms of participatory design, organizationa l accountability impact measurement, and qualitative research. I finished my third year at Pomona College in Los Angeles, where I study mathematics and philosophy.
