theme: jekyll-theme-minimal
title: Moe Sunami
description: I am taking a gap year to learn from digital rights and grassroots advocacy groups across the world. I finished my third year at Pomona College in Los Angeles, where I study mathematics and philosophy.
